/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Ian Lucas. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

// !!! THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. !!!

export const CS_english: Record<string, string> = {};