/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Ian Lucas. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

// !!! THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. !!!

import { CS_brazilian as brazilian } from "./brazilian.js";
export * from "./brazilian.js";
import { CS_bulgarian as bulgarian } from "./bulgarian.js";
export * from "./bulgarian.js";
import { CS_czech as czech } from "./czech.js";
export * from "./czech.js";
import { CS_danish as danish } from "./danish.js";
export * from "./danish.js";
import { CS_dutch as dutch } from "./dutch.js";
export * from "./dutch.js";
import { CS_english as english } from "./english.js";
export * from "./english.js";
import { CS_finnish as finnish } from "./finnish.js";
export * from "./finnish.js";
import { CS_french as french } from "./french.js";
export * from "./french.js";
import { CS_german as german } from "./german.js";
export * from "./german.js";
import { CS_greek as greek } from "./greek.js";
export * from "./greek.js";
import { CS_hungarian as hungarian } from "./hungarian.js";
export * from "./hungarian.js";
import { CS_italian as italian } from "./italian.js";
export * from "./italian.js";
import { CS_japanese as japanese } from "./japanese.js";
export * from "./japanese.js";
import { CS_koreana as koreana } from "./koreana.js";
export * from "./koreana.js";
import { CS_latam as latam } from "./latam.js";
export * from "./latam.js";
import { CS_norwegian as norwegian } from "./norwegian.js";
export * from "./norwegian.js";
import { CS_polish as polish } from "./polish.js";
export * from "./polish.js";
import { CS_portuguese as portuguese } from "./portuguese.js";
export * from "./portuguese.js";
import { CS_romanian as romanian } from "./romanian.js";
export * from "./romanian.js";
import { CS_russian as russian } from "./russian.js";
export * from "./russian.js";
import { CS_schinese as schinese } from "./schinese.js";
export * from "./schinese.js";
import { CS_spanish as spanish } from "./spanish.js";
export * from "./spanish.js";
import { CS_swedish as swedish } from "./swedish.js";
export * from "./swedish.js";
import { CS_tchinese as tchinese } from "./tchinese.js";
export * from "./tchinese.js";
import { CS_thai as thai } from "./thai.js";
export * from "./thai.js";
import { CS_turkish as turkish } from "./turkish.js";
export * from "./turkish.js";
import { CS_ukrainian as ukrainian } from "./ukrainian.js";
export * from "./ukrainian.js";
import { CS_vietnamese as vietnamese } from "./vietnamese.js";
export * from "./vietnamese.js";

export const CS_ITEM_TRANSLATION = { brazilian, bulgarian, czech, danish, dutch, english, finnish, french, german, greek, hungarian, italian, japanese, koreana, latam, norwegian, polish, portuguese, romanian, russian, schinese, spanish, swedish, tchinese, thai, turkish, ukrainian, vietnamese };