/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Ian Lucas. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

export function getItemsTsContents(items: unknown) {
    return `/*---------------------------------------------------------------------------------------------
  *  Copyright (c) Ian Lucas. All rights reserved.
  *  Licensed under the MIT License. See License.txt in the project root for license information.
  *--------------------------------------------------------------------------------------------*/
 
 import { CS_Item } from "./economy.js";
 
 // !!! THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. !!!
 
 // @ts-ignore
 export const CS_ITEMS: CS_Item[] = ${JSON.stringify(items)};`;
}
