name: publish

on:
  release:
    types: [published]

jobs:
  build:
    uses: ./.github/workflows/build.yml

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22.x
          registry-url: "https://registry.npmjs.org"

      - name: Install
        run: npm ci

      - name: Version
        run: npm version ${TAG_NAME} --git-tag-version=false
        env:
          TAG_NAME: ${{ github.ref_name }}

      - name: Publish Pre-release
        run: npm publish --provenance --access public --tag next
        if: github.event.release.prerelease
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}

      - name: Publish Release
        run: npm publish --provenance --access public
        if: !github.event.release.prerelease
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
